### ISSUE TITLE
Video Still Splitting 

### ISSUE THREAD

**Issue by iRashiD-AE** [rodit/SnapMod#188]
I was trying out the new camera features, but the video still splits even with the  'Disable Snap splitting' is enabled. 

@rodit Thank you for your great work 🌹

**Comment by Magna-Graecia** [comment]
Can confirm about the duplicates. If 'Disable Snap Splitting' is disabled, a 1 minute long video will get sent as 6 separate 1-minute long unsplit videos instead of 1 video that has been split into 6 segments lol wtf?

However, when 'Disable Snap Splitting' is enabled, I'm still able to send full unsplit videos as normal, so I'm not experiencing the same as iRashiD-AE in that regard. The same 1-minute video got sent as 1 single full unsplit snap with 'Disable Snap Splitting' enabled, not just the first 10 seconds.

**Comment by drickles** [comment]
I think the feature misses sometimes but it's really rare in my case. For me personally it works flawlessly most of the time. But I have twice experienced posting a 1 minute+ video that got splitted out of nowhere. One other time I tried positing a vid and only the first 10 seconds posted. But all in all deleting them and force closing snap and checking if I'm on the current module build and supported Snapchat APK tends to bring it back to working correctly.

**Comment by Magna-Graecia** [comment]
I honestly think they're AB testing something because after updating to the latest Snapchat and SnapMod, this wasn't happening at first. I was experiencing the issue I was before where the video would split fine, but then each segment would freeze midway beginning with the 2nd segment. Just now I tried sending the same exact video (1 minute long) with 'Disable Snap Splitting' disabled, and instead of being sent as 6 snaps where I would experience the issue I've been experiencing, this time it got sent as 6 separate 1-minute long videos lol. I haven't changed ANYTHING with Snapchat or SnapMod.

**Comment by Magna-Graecia** [comment]
@iRashiD-AE Turn off 'Force Source Encoding'. That's what's causing the duplicate snaps when 'Disable Snap Splitting' is turned off. I turned it off, and now the snaps split, but I still have the issue I was having previously, which is that they freeze beginning on the 2nd snap. You may not have this issue though.

**Comment by iRashiD-AE** [comment]
> @iRashiD-AE Turn off 'Force Source Encoding'. That's what's causing the duplicate snaps when 'Disable Snap Splitting' is turned off. I turned it off, and now the snaps split, but I still have the issue I was having previously, which is that they freeze beginning on the 2nd snap. You may not have this issue though.

Fixed by uploading videos from chat , do you have any idea how new resolution works? Cuz I have tried 4k-2k , 60-120fps but getting same results .

**Comment by rodit** [comment]
The duplication makes sense thinking about it. The length check must be confusing the splitting process meaning the media thinks it's supposed to be split, but also thinks it's less than 10 seconds so won't look further than that into the video. This should be a relatively easy fix.

Make sure 'Forcr Source Endcoding' is enabled @iRashiD-AE

**Comment by Magna-Graecia** [comment]
> The duplication makes sense thinking about it. The length check must be confusing the splitting process meaning the media thinks it's supposed to be split, but also thinks it's less than 10 seconds so won't look further than that into the video. This should be a relatively easy fix.
> 
> Make sure 'Forcr Source Endcoding' is enabled @iRashiD-AE

Makes sense.

I'm sure he already had it enabled, as it needs to be enabled for the duplication error to occur. He's probably confused in the same way that I am, which is not fully understanding how image/video resolution works haha. Can you explain? From my experience thus far, having 'Force Source Encoding' enabled and video/image resolution set to the highest, all I've noticed is that compression doesn't happen (except when posting to story, but there's a workaround to avoid it with that), which of course makes my image/video quality much better, but it's not like it makes my images/videos 4K or anything. 

I'm sure compression is being avoiding due solely to the 'Force Source Encoding' option, so what is image/video resolution doing? Is it making the camera record and upscale to the set resolution? Is it making saved images/videos that you send be upscaled to the set resolution? I don't fully understand.

**Comment by Magna-Graecia** [comment]
> > @iRashiD-AE Turn off 'Force Source Encoding'. That's what's causing the duplicate snaps when 'Disable Snap Splitting' is turned off. I turned it off, and now the snaps split, but I still have the issue I was having previously, which is that they freeze beginning on the 2nd snap. You may not have this issue though.
> 
> Fixed by uploading videos from chat , do you have any idea how new resolution works? Cuz I have tried 4k-2k , 60-120fps but getting same results .

What do you mean you fixed it by uploading from chat? You mean you went to a chat and used the in-chat gallery drawer to load the video into the camera edit window, then sent from there? I tried this just now, and it doesn't make any difference. It still gets sent as duplicates.

**Comment by iRashiD-AE** [comment]
> > > @iRashiD-AE Turn off 'Force Source Encoding'. That's what's causing the duplicate snaps when 'Disable Snap Splitting' is turned off. I turned it off, and now the snaps split, but I still have the issue I was having previously, which is that they freeze beginning on the 2nd snap. You may not have this issue though.
> > 
> > 
> > Fixed by uploading videos from chat , do you have any idea how new resolution works? Cuz I have tried 4k-2k , 60-120fps but getting same results .
> 
> What do you mean you fixed it by uploading from chat? You mean you went to a chat and used the in-chat gallery drawer to load the video into the camera edit window, then sent from there? I tried this just now, and it doesn't make any difference. It still gets sent as duplicates.

Yes , in-chat gallery drawer

With this settings
![Screenshot_20220613-100526_SnapMod~2](https://user-images.githubusercontent.com/52901789/173290050-1259e6a6-237d-4d74-a00c-3b73fef5eba1.png)

**Comment by Magna-Graecia** [comment]
> > > > @iRashiD-AE Turn off 'Force Source Encoding'. That's what's causing the duplicate snaps when 'Disable Snap Splitting' is turned off. I turned it off, and now the snaps split, but I still have the issue I was having previously, which is that they freeze beginning on the 2nd snap. You may not have this issue though.
> > > 
> > > 
> > > Fixed by uploading videos from chat , do you have any idea how new resolution works? Cuz I have tried 4k-2k , 60-120fps but getting same results .
> > 
> > 
> > What do you mean you fixed it by uploading from chat? You mean you went to a chat and used the in-chat gallery drawer to load the video into the camera edit window, then sent from there? I tried this just now, and it doesn't make any difference. It still gets sent as duplicates.
> 
> Yes , in-chat gallery drawer
> 
> With this settings ![Screenshot_20220613-100526_SnapMod~2](https://user-images.githubusercontent.com/52901789/173290050-1259e6a6-237d-4d74-a00c-3b73fef5eba1.png)

lol of course it works..... You have 'Disable Snap Splitting' enabled. Turn off 'Disable Snap Splitting' and enable 'Force Source Encoding' and you will see that snaps >10s get sent as duplicates instead of split.
